/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Curve001: THREE.Mesh;
    Curve002: THREE.Mesh;
    Curve003: THREE.Mesh;
    Curve004: THREE.Mesh;
    Curve008: THREE.Mesh;
    Curve010: THREE.Mesh;
    Curve011: THREE.Mesh;
    Curve013: THREE.Mesh;
    Curve014: THREE.Mesh;
    Curve015: THREE.Mesh;
    Curve016: THREE.Mesh;
    Curve017: THREE.Mesh;
    Curve019: THREE.Mesh;
    Curve021: THREE.Mesh;
    Curve022: THREE.Mesh;
    Curve025: THREE.Mesh;
    Curve026: THREE.Mesh;
    Curve029: THREE.Mesh;
    Curve031: THREE.Mesh;
    Curve035: THREE.Mesh;
    Curve037: THREE.Mesh;
    Curve038: THREE.Mesh;
    Curve039: THREE.Mesh;
    Curve040: THREE.Mesh;
    Curve043: THREE.Mesh;
    Curve044: THREE.Mesh;
    Curve045: THREE.Mesh;
    Curve046: THREE.Mesh;
    Curve047: THREE.Mesh;
    Curve048: THREE.Mesh;
    Curve049: THREE.Mesh;
    Curve050: THREE.Mesh;
    Curve051: THREE.Mesh;
    Curve052: THREE.Mesh;
    Curve053: THREE.Mesh;
    Curve054: THREE.Mesh;
    Curve055: THREE.Mesh;
    Curve056: THREE.Mesh;
    Curve057: THREE.Mesh;
    Curve058: THREE.Mesh;
    Curve059: THREE.Mesh;
    Curve060: THREE.Mesh;
    Curve061: THREE.Mesh;
    Curve062: THREE.Mesh;
    Curve063: THREE.Mesh;
    Curve064: THREE.Mesh;
    Curve065: THREE.Mesh;
    Curve066: THREE.Mesh;
    Curve067: THREE.Mesh;
    Curve068: THREE.Mesh;
    Curve069: THREE.Mesh;
    Curve070: THREE.Mesh;
    Curve071: THREE.Mesh;
    Curve072: THREE.Mesh;
    Curve073: THREE.Mesh;
    Curve074: THREE.Mesh;
    Curve075: THREE.Mesh;
    Curve076: THREE.Mesh;
    Curve077: THREE.Mesh;
    Curve078: THREE.Mesh;
    Curve079: THREE.Mesh;
    Curve080: THREE.Mesh;
    Curve081: THREE.Mesh;
    Curve082: THREE.Mesh;
    Curve083: THREE.Mesh;
    Curve084: THREE.Mesh;
    Curve085: THREE.Mesh;
    Curve086: THREE.Mesh;
    Curve087: THREE.Mesh;
    Curve088: THREE.Mesh;
    Curve089: THREE.Mesh;
    Curve090: THREE.Mesh;
    Curve091: THREE.Mesh;
    Curve092: THREE.Mesh;
    Curve093: THREE.Mesh;
    Curve094: THREE.Mesh;
    Curve095: THREE.Mesh;
    Curve096: THREE.Mesh;
    Curve097: THREE.Mesh;
    Curve098: THREE.Mesh;
    Curve099: THREE.Mesh;
    Curve100: THREE.Mesh;
    Curve101: THREE.Mesh;
    Curve102: THREE.Mesh;
    Curve103: THREE.Mesh;
    Curve104: THREE.Mesh;
    Curve105: THREE.Mesh;
    Curve106: THREE.Mesh;
    Curve107: THREE.Mesh;
    Curve108: THREE.Mesh;
    Curve109: THREE.Mesh;
    Curve110: THREE.Mesh;
    Curve111: THREE.Mesh;
    Curve112: THREE.Mesh;
    Curve113: THREE.Mesh;
    Curve114: THREE.Mesh;
    Curve115: THREE.Mesh;
    Curve116: THREE.Mesh;
    Curve117: THREE.Mesh;
    Curve118: THREE.Mesh;
    Curve119: THREE.Mesh;
    Curve120: THREE.Mesh;
    Curve121: THREE.Mesh;
    Curve122: THREE.Mesh;
    Curve123: THREE.Mesh;
    Curve124: THREE.Mesh;
    Curve125: THREE.Mesh;
    Curve126: THREE.Mesh;
    Curve127: THREE.Mesh;
    Curve128: THREE.Mesh;
    Curve129: THREE.Mesh;
    Curve130: THREE.Mesh;
    Curve131: THREE.Mesh;
    Curve132: THREE.Mesh;
    Curve133: THREE.Mesh;
    Curve134: THREE.Mesh;
    Curve135: THREE.Mesh;
    Curve136: THREE.Mesh;
    Curve137: THREE.Mesh;
    Curve138: THREE.Mesh;
    Curve139: THREE.Mesh;
    Curve140: THREE.Mesh;
    Curve141: THREE.Mesh;
    Curve142: THREE.Mesh;
    Curve143: THREE.Mesh;
    Curve144: THREE.Mesh;
    Curve145: THREE.Mesh;
    Curve146: THREE.Mesh;
    Curve147: THREE.Mesh;
    Curve148: THREE.Mesh;
    Curve149: THREE.Mesh;
    Curve150: THREE.Mesh;
    Curve151: THREE.Mesh;
    Curve152: THREE.Mesh;
    Curve153: THREE.Mesh;
    Curve154: THREE.Mesh;
    Curve155: THREE.Mesh;
    Curve156: THREE.Mesh;
    Curve157: THREE.Mesh;
    Curve158: THREE.Mesh;
    Curve159: THREE.Mesh;
    Curve160: THREE.Mesh;
    Curve161: THREE.Mesh;
    Curve162: THREE.Mesh;
    Curve163: THREE.Mesh;
    Curve164: THREE.Mesh;
    Curve165: THREE.Mesh;
    Curve166: THREE.Mesh;
    Curve167: THREE.Mesh;
    Curve168: THREE.Mesh;
    Curve169: THREE.Mesh;
    Curve170: THREE.Mesh;
    Curve171: THREE.Mesh;
    Curve172: THREE.Mesh;
    Curve173: THREE.Mesh;
    Curve174: THREE.Mesh;
    Curve175: THREE.Mesh;
    Curve176: THREE.Mesh;
    Curve177: THREE.Mesh;
    Curve178: THREE.Mesh;
    Curve179: THREE.Mesh;
    Curve180: THREE.Mesh;
    Curve181: THREE.Mesh;
    Curve182: THREE.Mesh;
    Curve183: THREE.Mesh;
    Curve184: THREE.Mesh;
    Curve185: THREE.Mesh;
    Curve186: THREE.Mesh;
    Curve187: THREE.Mesh;
    Curve188: THREE.Mesh;
    Curve189: THREE.Mesh;
    Curve190: THREE.Mesh;
    Curve191: THREE.Mesh;
    Curve192: THREE.Mesh;
    Curve193: THREE.Mesh;
    Curve194: THREE.Mesh;
    Curve195: THREE.Mesh;
    Curve196: THREE.Mesh;
    Curve197: THREE.Mesh;
    Curve198: THREE.Mesh;
    Curve199: THREE.Mesh;
    Curve200: THREE.Mesh;
    Curve203: THREE.Mesh;
    Curve204: THREE.Mesh;
    Curve205: THREE.Mesh;
    Curve206: THREE.Mesh;
    Curve207: THREE.Mesh;
    Curve208: THREE.Mesh;
    Curve209: THREE.Mesh;
    Curve210: THREE.Mesh;
    Curve211: THREE.Mesh;
    Curve212: THREE.Mesh;
    Curve213: THREE.Mesh;
    Curve214: THREE.Mesh;
    Curve215: THREE.Mesh;
    Curve216: THREE.Mesh;
    Curve217: THREE.Mesh;
    Curve218: THREE.Mesh;
    Curve219: THREE.Mesh;
    Curve220: THREE.Mesh;
    Curve221: THREE.Mesh;
    Curve222: THREE.Mesh;
  };
  materials: {
    ['c black']: THREE.MeshPhysicalMaterial;
    ['c white']: THREE.MeshPhysicalMaterial;
    grid: THREE.MeshPhysicalMaterial;
  };
};

type ActionName =
  | 'Empty.002Action'
  | 'Empty.001Action'
  | 'EmptyAction'
  | 'BASEAction';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF('/coin3.glb') as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty002" rotation={[-0.92, -0.23, 1.36]}>
          <group name="Empty001" rotation={[0, 0, -2.8]}>
            <group name="Empty" rotation={[2.33, 0, 0]}>
              <group name="BASE" rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
                <mesh
                  name="Cylinder001"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder001.geometry}
                  material={materials['c black']}
                />
                <mesh
                  name="Cylinder001_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder001_1.geometry}
                  material={materials['c white']}
                />
                <mesh
                  name="Cylinder001_2"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder001_2.geometry}
                  material={materials.grid}
                />
                <mesh
                  name="Curve001"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve001.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve002"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve002.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve003"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve003.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve004"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve004.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve008"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve008.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve010"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve010.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve011"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve011.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve013"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve013.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve014"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve014.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve015"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve015.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve016"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve016.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve017"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve017.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve019"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve019.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve021"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve021.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve022"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve022.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve025"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve025.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve026"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve026.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve029"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve029.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve031"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve031.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve035"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve035.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve037"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve037.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve038"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve038.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve039"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve039.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve040"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve040.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve043"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve043.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve044"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve044.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve045"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve045.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve046"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve046.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve047"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve047.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve048"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve048.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve049"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve049.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve050"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve050.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve051"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve051.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve052"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve052.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve053"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve053.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve054"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve054.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve055"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve055.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve056"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve056.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve057"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve057.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve058"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve058.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve059"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve059.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve060"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve060.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve061"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve061.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve062"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve062.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve063"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve063.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve064"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve064.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve065"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve065.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve066"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve066.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve067"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve067.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve068"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve068.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve069"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve069.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve070"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve070.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve071"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve071.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve072"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve072.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve073"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve073.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve074"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve074.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve075"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve075.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve076"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve076.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve077"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve077.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve078"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve078.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve079"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve079.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve080"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve080.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve081"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve081.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve082"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve082.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve083"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve083.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve084"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve084.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve085"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve085.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve086"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve086.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve087"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve087.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve088"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve088.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve089"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve089.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve090"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve090.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve091"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve091.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve092"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve092.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve093"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve093.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve094"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve094.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve095"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve095.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve096"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve096.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve097"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve097.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve098"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve098.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve099"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve099.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve100.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve101"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve101.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve102"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve102.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve103"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve103.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve104"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve104.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve105"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve105.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve106.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve107"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve107.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve108"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve108.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve109"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve109.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve110"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve110.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve111"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve111.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve112.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve113"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve113.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve114"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve114.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve115"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve115.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve116"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve116.geometry}
                  material={materials['c white']}
                  position={[0.27, -0.16, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                />
                <mesh
                  name="Curve117"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve117.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve118.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve119"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve119.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve120"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve120.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve121.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve122.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve123"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve123.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve124.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve125"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve125.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve126.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve127"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve127.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve128.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve129"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve129.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve130.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve131"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve131.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve132"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve132.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve133.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve134.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve135"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve135.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve136.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve137"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve137.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve138.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve139.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve140"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve140.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve141"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve141.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve142.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve143"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve143.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve144.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve145.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve146"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve146.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve147"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve147.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve148.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve149"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve149.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve150"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve150.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve151"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve151.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve152"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve152.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve153"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve153.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve154.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve155"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve155.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve156"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve156.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve157.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve158"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve158.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve159"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve159.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve160"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve160.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve161"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve161.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve162"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve162.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve163"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve163.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve164"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve164.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve165"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve165.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve166"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve166.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve167"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve167.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve168"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve168.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve169"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve169.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve170"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve170.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve171"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve171.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve172"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve172.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve173"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve173.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve174"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve174.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve175"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve175.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve176"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve176.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve177"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve177.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve178"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve178.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve179"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve179.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve180"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve180.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve181"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve181.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve182"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve182.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve183"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve183.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve184"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve184.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve185"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve185.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve186"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve186.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve187"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve187.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve188"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve188.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve189"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve189.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve190"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve190.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve191"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve191.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve192"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve192.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve193"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve193.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve194"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve194.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve195"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve195.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve196"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve196.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve197"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve197.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve198"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve198.geometry}
                  material={materials['c white']}
                  position={[-0.27, -0.16, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                />
                <mesh
                  name="Curve199"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve199.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve200"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve200.geometry}
                  material={materials['c white']}
                  position={[0.23, -0.14, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 6, Math.PI]}
                  scale={0.87}
                />
                <mesh
                  name="Curve203"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve203.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve204"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve204.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve205"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve205.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve206"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve206.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve207"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve207.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve208"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve208.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve209"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve209.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve210"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve210.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve211"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve211.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve212"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve212.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve213"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve213.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve214"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve214.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve215"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve215.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve216"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve216.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve217"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve217.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve218"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve218.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve219"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve219.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve220"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve220.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve221"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve221.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
                <mesh
                  name="Curve222"
                  castShadow
                  receiveShadow
                  geometry={nodes.Curve222.geometry}
                  material={materials['c white']}
                  position={[-0.23, -0.14, 0.01]}
                  rotation={[Math.PI / 2, -Math.PI / 6, 0]}
                  scale={0.87}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/coin3.glb');
